# Generated by Django 4.1.2 on 2023-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugsn',
            name='name',
            field=models.CharField(default='dasda', max_length=255, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
