# Generated by Django 4.1.2 on 2023-07-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0002_ugsn_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprogram',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterUniqueTogether(
            name='educationprogram',
            unique_together={('name', 'speciality')},
        ),
    ]
