# Generated by Django 4.1.2 on 2023-07-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0003_alter_educationprogram_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Код'),
        ),
    ]
