# Generated by Django 4.1.2 on 2023-07-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0004_alter_speciality_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='category_name',
            field=models.CharField(max_length=255, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterUniqueTogether(
            name='competence',
            unique_together={('name', 'code')},
        ),
    ]
