# Generated by Django 4.1.2 on 2023-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0005_alter_competence_category_name_alter_competence_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competence',
            name='level',
            field=models.CharField(choices=[('Бакалавриат', 'Bachelor'), ('Специалитет', 'Specialist'), ('Магистратура', 'Master')], default='dad', max_length=20, verbose_name='Уровень образования'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=700, verbose_name='Наименование'),
        ),
        migrations.AlterUniqueTogether(
            name='competence',
            unique_together={('name', 'code', 'level')},
        ),
    ]
