# Generated by Django 4.1.2 on 2023-07-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0006_alter_competence_unique_together_competence_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='category_name',
            field=models.CharField(max_length=500, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
    ]
