# Generated by Django 4.1.2 on 2023-07-30 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('dicts', '0006_alter_competence_unique_together_competence_level_and_more'),
        ('testing', '0002_alter_test_subjects_alter_test_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='subjects',
        ),
        migrations.AddField(
            model_name='answer',
            name='assigned_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.assignedtest', verbose_name='Назначенный тест'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Одиночный выбор', 'Single Choice'), ('Множественный выбор', 'Multiple Choice'), ('Установление соответствия', 'Matching'), ('Установления последовательности', 'Sequencing'), ('Дополнение', 'Addition'), ('Свободное изложение', 'Free Presentation')], default='asda', max_length=40, verbose_name='Тип вопроса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dicts.subject', verbose_name='Предмет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.JSONField(default=dict, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='assignedtest',
            name='end_time',
            field=models.DateTimeField(verbose_name='Время окончания теста'),
        ),
        migrations.AlterField(
            model_name='assignedtest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала теста'),
        ),
        migrations.AlterField(
            model_name='assignedtest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='assignedtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(default=dict, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.teacher', verbose_name='Преподаватель'),
        ),
    ]
