# Generated by Django 4.1.2 on 2023-07-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_remove_test_subjects_answer_assigned_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Одиночный выбор', 'Single Choice'), ('Множественный выбор', 'Multiple Choice'), ('Установление соответствия', 'Matching'), ('Установления последовательности', 'Sequencing'), ('Дополнение', 'Addition'), ('Свободное изложение', 'Free Presentation')], max_length=100, verbose_name='Тип вопроса'),
        ),
    ]
